name: Create Release ZIP

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP Archive
        run: |
          zip -r dlds.zip data pack.mcmeta readme.md

      - name: Upload ZIP to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dlds.zip
          token: ${{ secrets.GITHUB_TOKEN }}
